### ISSUE TITLE
付録用のソースコード

### ISSUE THREAD

**Issue by kuroda** [oiax/ex_book1#3]
`appendix` ディレクトリの下に `ch07-1.exs` のようなファイル名で作成する。

**Comment by makoto-atarashi** [comment]
@kuroda 
回答がスクリプト形式ではないもの（単語を答えさせるものや正誤問題）の場合はどうしますか？

**Comment by makoto-atarashi** [comment]
@kuroda 
完了しましたのでイシュークローズします。
